### ISSUE TITLE
Not an issue just a suggestion 

### ISSUE THREAD

**Issue by viyoriya** [OliverLew/xdg-xmenu#10]
I have moved some variables in config header file.  Its an idea its up to you to change anyway attaching the diff and header file have a look you may get better idea.
Thanks

[xdg-xmenu-withConfigFile.tar.gz](https://github.com/xlucn/xdg-xmenu/files/11523040/xdg-xmenu-withConfigFile.tar.gz)

**Comment by xlucn** [comment]
Thanks for this. I am open to adding config files to it.

Actually, this inspired me. Instead of the suckless-style header file, what about an ini/cfg-style config file? Since this program already reads tons of desktop entry files already with `libinih`, doesn't hurt to add one more.

**Comment by viyoriya** [comment]
Cool.  I am not a C developer I just quickly learned how to make a  Makefile tried based on suckless code. As you said you already reading an ini file then there is no point for importing another (file reading operation is expensive AFAIK than pre compiled code). This C code is really faster compared to old bash script :)

**Comment by xlucn** [comment]
Actually, xdg-xmenu usually reads dozens to hundreads of desktop entry files, costing 10~100ms in startup. You can find out with `time xdg-xmenu -d`. So, reading one more (and it will be a small config file, so <~1ms) on top of that probably won't affect the start up speed that much. So it's just a matter of preference I guess.

**Comment by viyoriya** [comment]
That's cool take your time  :) .Thanks. Wow the time command is so fast :)
