### ISSUE TITLE
Show xdg-xmenu as a submenu integrated in xmenu

### ISSUE THREAD

**Issue by lo-yak** [OliverLew/xdg-xmenu#11]
Hey, right now I have my `xmenu.sh` like this:
```

#!/bin/sh

xmenu <<EOF | sh &
Terminal	alacritty
Web Browser	firefox
File Manager	thunar
Text Editor	geany

Applications	xdg-xmenu -I

Exit			/home/andrea/bin/powermenu.sh
EOF

```

This way to open xdg-xmenu I have to click on `Applications`.

Is there a way to have xdg-xmenu embedded in xmenu, instead of having to click on `Applications`?

**Comment by xlucn** [comment]
This is a feature I have long considered adding to xdg-xmenu, which uses a file as wrapper and insert the menu into it. It's not hard to implement, I am just lazy :)

Actually, I find out it can be temporarily done quite nicely with (it simply add a tab in front of the lines to make them a submenu)
```sh
#!/bin/sh

xmenu <<EOF | sh &
Terminal	alacritty
Web Browser	firefox
File Manager	thunar
Text Editor	geany

Applications
$(xdg-xmenu -dI | sed 's/.*/\t\0/')

Exit			/home/andrea/bin/powermenu.sh
EOF
```
Remove the `-I` option have icons. Please try if it works for you.

I guess I can keep being lazy, then?

**Comment by lo-yak** [comment]
I'm happy.
Have a good laziness, you deserve it.

**Comment by lo-yak** [comment]
Actually, jokes aside, just another thing. It would be great to have all the categories of xdg-xmenu directly in xmenu, instead of having to put the cursor on `Applications >` to view them. Would it be possible?

You know, I'm lazy too...

**Comment by xlucn** [comment]
That should be easier:
```
#!/bin/sh

xmenu <<EOF | sh &
Terminal	alacritty
Web Browser	firefox
File Manager	thunar
Text Editor	geany

$(xdg-xmenu -dI)

Exit			/home/andrea/bin/powermenu.sh
EOF
```

**Comment by lo-yak** [comment]
of course it is, sorry for the dumb question and thank you!
