### ISSUE TITLE
xdg-xmenu crashes if launched with -I

### ISSUE THREAD

**Issue by lo-yak** [OliverLew/xdg-xmenu#12]
Okay, here's a weird one, honestly I have no clue what's going on.
Suddendly, if I run `xdg-xmenu -I` I have the usual menu, but instead of 
```
Others > Jitsi Meet
	Rofi
	Rofi theme selector
```

Now I have
```
Others >
Jitsi Meet > Rofi
	Rofi theme selector
```

And if I put the cursor on `Others`, it crashes.

I tried to uninstall `Jitsi Meet` and the result became
```
Others >
Rofi > Rofi theme selector
```

So the problem is not Jitsi Meet.

If I run `xdg-xmenu`, the menu is back to normal and I have no problems.
Do you have any idea what the problem could be, and why if I remove the icons then my .desktops files without  a specified `Categories` jump out from `Others` and create a new category, with the name of one of them as a title of the menu and the others as a submenu items?

I hope I have explained clearly the issue, if not I'll provide some screenshot as english is not my first language and this is very weird.
Thank you.

Edit: I tried to format it to look decent but I give up.

**Comment by xlucn** [comment]
I am not so sure what's happening here, maybe something is missing and xmenu does not recognize the resulting format.

Could you paste the output of `xdg-xmenu -Id`, maybe just the few lines starting from "Others", until the next category, if xdg-xmenu only crashes when opening submenu "Others".

**Comment by lo-yak** [comment]
> Could you paste the output of xdg-xmenu -Id

```
Others
		
	Rofi	rofi -show
	Rofi Theme Selector	rofi-theme-selector
Settings
```

Seems pretty normal to me...but the first empty line exists only in this category! Maybe is that, somehow?

**Comment by xlucn** [comment]
I can reproduce with an empty desktop entry file (at least one without `Name` and `GenericName`). It should count as a bug, since this is then a invalid desktop entry file.

So, for now, you can check `$XDG_DATA_HOME` and `$XDG_DATA_DIRS` for empty `*.desktop` files, or at least empty `Name` and `GenericName` fields.

If you do find one such file, remove it and won't crash again, then it is confirmed. But still, keep the issue open, I will fix the code to account for invalid entries later.

**Comment by lo-yak** [comment]
Found it!
I had` ~/.local/share/applications/audacity.desktop` that was totally empty, for some reason...I removed it and now it's all good.
Strange that this problem appears only if removing icons though.
Anyway, solved. Thank you so much!

**Comment by lo-yak** [comment]
Sorry, the habit... lol
