### ISSUE TITLE
Empty prefix IMG: in the submenu titles

### ISSUE THREAD

**Issue by raven2cz** [OliverLew/xdg-xmenu#2]
I found next error in the generation:

IMG: Science
IMG:/home/box/.cache/xdg-xmenu/icons/cantor.png Cantor (Frontend to Mathematical Software) cantor -qwindowicon cantor -qwindowtitle
R (environment for statistical computing) xterm -e R
IMG:/home/box/.cache/xdg-xmenu/icons/octave.png GNU Octave /usr/bin/octave --gui
IMG:/home/box/.cache/xdg-xmenu/icons/kalgebra.png KAlgebra (Graph Calculator) kalgebra
IMG:/home/box/.cache/xdg-xmenu/icons/kalgebra.png KAlgebra Mobile (Pocket Graph Calculator) kalgebramobile
IMG:/home/box/.cache/xdg-xmenu/icons/kalzium.png Kalzium (Periodic Table of Elements) kalzium -qwindowtitle
IMG:/home/box/.cache/xdg-xmenu/icons/marble.png KDE Marble (Virtual Globe) marble
IMG:/home/box/.cache/xdg-xmenu/icons/libreoffice-math.png LibreOffice Math (Formula Editor) libreoffice --math
IMG:/home/box/.cache/xdg-xmenu/icons/rocs.png Rocs (Rocs Graph Theory) rocs -qwindowtitle
Julia xterm -e julia
Singular xterm -e Singular

If the image doesn't exist in the app line, the prefix IMG is correctly removed, e.g. R and Singular lines.
But if the image missing for submenu names, there is still present IMG: prefix with empty icon which cause error message in the xmenu program:  xmenu: cannot load icon
The prefix IMG:  cannot be generated for submenu titles if there is no image for it, similar as app lines.

**Comment by xlucn** [comment]
Thanks for pointing it out! The latest commit should fix it.
