### ISSUE TITLE
empty .local/share/applications dir and throws error

### ISSUE THREAD

**Issue by viyoriya** [OliverLew/xdg-xmenu#6]
I have empty .local/share/applications  dir and it throws error 
a quick fix 

after line no 178 please add this check  (or a be better solution )
    [[ ! "$(ls -A $appdir)" ]] && continue
 

Thanks for the xdg-menu :)

**Comment by xlucn** [comment]
Thanks for the catch! I found that if the folder has other files, could also cause issues. I pushed a similar commit, should be solving the issue.

**Comment by viyoriya** [comment]
:+1:
