### ISSUE TITLE
Add an option to exclude empty app categories

### ISSUE THREAD

**Issue by akdevservices** [OliverLew/xdg-xmenu#7]
Add an option to exclude empty app categories from the generated app menu. The patch is attached. And please tag the new version with the latest changes.
[no-empty-categories.patch.gz](https://github.com/OliverLew/xdg-xmenu/files/8643219/no-empty-categories.patch.gz)

**Comment by xlucn** [comment]
Thanks for the patch. I think I will go one step further making empty categories hidden by default and providing an option to show them.
