### ISSUE TITLE
Do not show GenericName by default

### ISSUE THREAD

**Issue by akdevservices** [OliverLew/xdg-xmenu#8]
Do not show GenericName by default to make the generated menu more concise. Add an option to show GenericName (old behavior). The proposed patch is attached.

[show-genname.patch.gz](https://github.com/OliverLew/xdg-xmenu/files/8717886/show-genname.patch.gz)

**Comment by xlucn** [comment]
My consideration was that some application names are not that self-explanatory. So, showing their generic name will help providing more information.

I might instead add an opposite option to hide the generic name, while keeping the current behavior.

**Comment by akdevservices** [comment]
> I might instead add an opposite option to hide the generic name, while keeping the current behavior.

That works for me too. I just wanted a way to make a context menu more compact.
